name: 'GSA/odp-code-repository-commit-rules'
description: 'This repository maintains a list of rules for finding secrets in a repository. These rules can used for pre-commit hook and post commit repository scanning.'
license: cc0-1.0
openSourceProject: 1
governmentWideReuseProject: 1
tags:
    - open-source
    - opensource
    - grace
    - devsecops
contact:
    email: ociso-devsecops@gsa.gov
