version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/GSA/odp-code-repository-commit-rules
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            make test
workflows:
  version: 2

  test:
    jobs:
      - test